#!/bin/bash

make -j36 \
QEMU_VIRTFS_ENABLE=y \
QEMU_USERNET_ENABLE=y \
CFG_SECURE_DATA_PATH=n \
CFG_TA_ASLR=n \
CFG_CORE_ASLR=n \
CFG_PKCS11_TA=y \
CFG_TEE_CORE_LOG_LEVEL=2 \
CFG_TEE_TA_LOG_LEVEL=3 \
CFG_USER_TA_TARGETS=ta_arm64 \
CFG_TEE_CORE_MALLOC_DEBUG=y \
BR2_FORTIFY_SOURCE_NONE=y \
GDBSERVER=y
