#!/bin/bash

#make -j1 CFG_SECURE_DATA_PATH=n CFG_PKCS11_TA=y CFG_USER_TA_TARGETS=ta_arm64 CFG_TEE_TA_LOG_LEVEL=2 CFG_CORE_ASLR=n GDBSERVER=y
#make -j36 CFG_SECURE_DATA_PATH=n CFG_PKCS11_TA=y CFG_USER_TA_TARGETS=ta_arm64 CFG_TEE_TA_LOG_LEVEL=2 CFG_CORE_ASLR=n GDBSERVER=y
make -j36 CFG_SECURE_DATA_PATH=n CFG_PKCS11_TA=y CFG_USER_TA_TARGETS=ta_arm64 CFG_TEE_TA_LOG_LEVEL=3 CFG_CORE_ASLR=n GDBSERVER=y
